spring:
  kafka:
    consumer:
      bootstrap-servers: pkc-921jm.us-east-2.aws.confluent.cloud:9092
      group-id: group-message
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages : com.gaurav.kafka.kafkaconsumer.dto





server:
  port: 9292